/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MasukkanData.java
 *
 * Created on Nov 2, 2011, 6:38:36 AM
 */

package panel;

/**
 *
 * @author zaf
 */
public class MasukkanData extends javax.swing.JPanel {

    /** Creates new form MasukkanData */
    public MasukkanData() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new component.panel.Menu();
        panelGuru = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        labelGURU = new javax.swing.JLabel();
        fieldGuru = new javax.swing.JTextField();
        labelNamaGuru = new javax.swing.JLabel();
        simpanGuru = new javax.swing.JButton();
        panelStatus = new javax.swing.JPanel();
        labelSTATUS = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaStatus = new javax.swing.JTextArea();
        panelMatpel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        simpanMatpel = new javax.swing.JButton();
        inputMatpel = new javax.swing.JTextField();
        labelMatpel = new javax.swing.JLabel();
        labelGuru = new javax.swing.JLabel();
        comboBoxGuru = new javax.swing.JComboBox();
        labelMATPEL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spinnerJam = new javax.swing.JSpinner();

        panelGuru.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelGURU.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelGURU.setText("Guru");

        fieldGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldGuruKeyPressed(evt);
            }
        });

        labelNamaGuru.setText("Nama Guru");

        simpanGuru.setText("Simpan");
        simpanGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanGuruActionPerformed(evt);
            }
        });
        simpanGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                simpanGuruKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelGuruLayout = new javax.swing.GroupLayout(panelGuru);
        panelGuru.setLayout(panelGuruLayout);
        panelGuruLayout.setHorizontalGroup(
            panelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGURU)
                .addContainerGap(172, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGroup(panelGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(labelNamaGuru)
                    .addComponent(simpanGuru))
                .addContainerGap())
        );
        panelGuruLayout.setVerticalGroup(
            panelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGURU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNamaGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanGuru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelSTATUS.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelSTATUS.setText("Status");

        areaStatus.setColumns(20);
        areaStatus.setEditable(false);
        areaStatus.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        areaStatus.setForeground(new java.awt.Color(1, 1, 1));
        areaStatus.setLineWrap(true);
        areaStatus.setRows(5);
        areaStatus.setAutoscrolls(true);
        jScrollPane1.setViewportView(areaStatus);

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSTATUS)
                .addContainerGap(206, Short.MAX_VALUE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSTATUS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMatpel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        simpanMatpel.setText("Simpan");
        simpanMatpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanMatpelActionPerformed(evt);
            }
        });

        inputMatpel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputMatpelKeyPressed(evt);
            }
        });

        labelMatpel.setText("Mata pelajaran");

        labelGuru.setText("Guru");

        comboBoxGuru.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxGuruItemStateChanged(evt);
            }
        });
        comboBoxGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGuruActionPerformed(evt);
            }
        });
        comboBoxGuru.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                comboBoxGuruHierarchyChanged(evt);
            }
        });
        comboBoxGuru.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboBoxGuruPropertyChange(evt);
            }
        });
        comboBoxGuru.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                comboBoxGuruVetoableChange(evt);
            }
        });

        labelMATPEL.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelMATPEL.setText("Mata Pelajaran");

        jLabel1.setText("Jam");
        jLabel1.setToolTipText("Jumlah jam ajar dalam 1 minggu");

        spinnerJam.setToolTipText("Jumlah jam ajar dalam 1 minggu");

        javax.swing.GroupLayout panelMatpelLayout = new javax.swing.GroupLayout(panelMatpel);
        panelMatpel.setLayout(panelMatpelLayout);
        panelMatpelLayout.setHorizontalGroup(
            panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMATPEL)
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGroup(panelMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpanMatpel)
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(panelMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(labelMatpel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatpelLayout.createSequentialGroup()
                        .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(spinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGuru)
                            .addComponent(comboBoxGuru, 0, 162, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelMatpelLayout.setVerticalGroup(
            panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMATPEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMatpel)
                .addGap(4, 4, 4)
                .addComponent(inputMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelGuru))
                .addGap(4, 4, 4)
                .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanMatpel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panelMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
            .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menu1Layout.createSequentialGroup()
                            .addComponent(panelGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldGuruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldGuruKeyPressed
        // TODO add your handling code here:
        simpanGuru.setEnabled(true);
}//GEN-LAST:event_fieldGuruKeyPressed

    private void simpanGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanGuruActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_simpanGuruActionPerformed

    private void simpanGuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_simpanGuruKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_simpanGuruKeyTyped

    private void simpanMatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanMatpelActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_simpanMatpelActionPerformed

    private void inputMatpelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMatpelKeyPressed
        // TODO add your handling code here:
        simpanMatpel.setEnabled(true);
        spinnerJam.setEnabled(true);
        comboBoxGuru.setEnabled(true);
}//GEN-LAST:event_inputMatpelKeyPressed

    private void comboBoxGuruItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxGuruItemStateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruItemStateChanged

    private void comboBoxGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGuruActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruActionPerformed

    private void comboBoxGuruHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_comboBoxGuruHierarchyChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruHierarchyChanged

    private void comboBoxGuruPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboBoxGuruPropertyChange
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruPropertyChange

    private void comboBoxGuruVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_comboBoxGuruVetoableChange
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruVetoableChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaStatus;
    private javax.swing.JComboBox comboBoxGuru;
    private javax.swing.JTextField fieldGuru;
    private javax.swing.JTextField inputMatpel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelGURU;
    private javax.swing.JLabel labelGuru;
    private javax.swing.JLabel labelMATPEL;
    private javax.swing.JLabel labelMatpel;
    private javax.swing.JLabel labelNamaGuru;
    private javax.swing.JLabel labelSTATUS;
    private component.panel.Menu menu1;
    private javax.swing.JPanel panelGuru;
    private javax.swing.JPanel panelMatpel;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JButton simpanGuru;
    private javax.swing.JButton simpanMatpel;
    private javax.swing.JSpinner spinnerJam;
    // End of variables declaration//GEN-END:variables

}
