/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PerbaikiData.java
 *
 * Created on Nov 2, 2011, 7:41:53 AM
 */

package panel;

/**
 *
 * @author zaf
 */
public class PerbaikiData extends javax.swing.JPanel {

    /** Creates new form PerbaikiData */
    public PerbaikiData() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new component.panel.Menu();
        jPanel1 = new javax.swing.JPanel();
        labelGURU = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listGuru = new javax.swing.JList();
        fieldGuru = new javax.swing.JTextField();
        simpanGuru = new javax.swing.JButton();
        hapusGuru = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelMATPEL = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMatpel = new javax.swing.JList();
        fieldMatpel = new javax.swing.JTextField();
        simpanMatpel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelGuru = new javax.swing.JLabel();
        comboBoxGuru = new javax.swing.JComboBox();
        hapusMatpel = new javax.swing.JButton();
        spinnerJam = new javax.swing.JSpinner();
        panelStatus = new javax.swing.JPanel();
        labelSTATUS = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaStatus = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelGURU.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelGURU.setText("Guru");

        listGuru.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listGuruValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listGuru);

        simpanGuru.setText("Simpan");
        simpanGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanGuruActionPerformed(evt);
            }
        });

        hapusGuru.setText("Hapus");
        hapusGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusGuruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGURU)
                .addContainerGap(127, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpanGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusGuru)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGURU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanGuru)
                    .addComponent(hapusGuru))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelMATPEL.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelMATPEL.setText("Mata Pelajaran");

        listMatpel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMatpelValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listMatpel);

        simpanMatpel.setText("Simpan");
        simpanMatpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanMatpelActionPerformed(evt);
            }
        });

        jLabel1.setText("Guru");

        labelGuru.setText("Jam");

        comboBoxGuru.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxGuruItemStateChanged(evt);
            }
        });
        comboBoxGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGuruActionPerformed(evt);
            }
        });
        comboBoxGuru.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                comboBoxGuruHierarchyChanged(evt);
            }
        });
        comboBoxGuru.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboBoxGuruPropertyChange(evt);
            }
        });
        comboBoxGuru.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                comboBoxGuruVetoableChange(evt);
            }
        });

        hapusMatpel.setText("Hapus");
        hapusMatpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusMatpelActionPerformed(evt);
            }
        });

        spinnerJam.setToolTipText("Jumlah jam ajar dalam 1 minggu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMATPEL)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGuru)
                            .addComponent(spinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxGuru, 0, 151, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(fieldMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpanMatpel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusMatpel)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMATPEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGuru)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanMatpel)
                    .addComponent(hapusMatpel))
                .addContainerGap())
        );

        panelStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelSTATUS.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelSTATUS.setText("Status");

        areaStatus.setColumns(20);
        areaStatus.setEditable(false);
        areaStatus.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        areaStatus.setForeground(new java.awt.Color(1, 1, 1));
        areaStatus.setLineWrap(true);
        areaStatus.setRows(5);
        areaStatus.setAutoscrolls(true);
        jScrollPane3.setViewportView(areaStatus);

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSTATUS)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSTATUS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
            .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu1Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menu1Layout.createSequentialGroup()
                            .addComponent(panelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(menu1Layout.createSequentialGroup()
                            .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(9, 9, 9)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listGuruValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listGuruValueChanged
        // TODO add your handling code here:
        fieldGuru.setText((String)listGuru.getSelectedValue());
        simpanGuru.setEnabled(true);
        hapusGuru.setEnabled(true);
}//GEN-LAST:event_listGuruValueChanged

    private void simpanGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanGuruActionPerformed

    private void hapusGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusGuruActionPerformed

    private void listMatpelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMatpelValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listMatpelValueChanged

    private void simpanMatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanMatpelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanMatpelActionPerformed

    private void comboBoxGuruItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxGuruItemStateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruItemStateChanged

    private void comboBoxGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGuruActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruActionPerformed

    private void comboBoxGuruHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_comboBoxGuruHierarchyChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruHierarchyChanged

    private void comboBoxGuruPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboBoxGuruPropertyChange
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruPropertyChange

    private void comboBoxGuruVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_comboBoxGuruVetoableChange
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruVetoableChange

    private void hapusMatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusMatpelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusMatpelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaStatus;
    private javax.swing.JComboBox comboBoxGuru;
    private javax.swing.JTextField fieldGuru;
    private javax.swing.JTextField fieldMatpel;
    private javax.swing.JButton hapusGuru;
    private javax.swing.JButton hapusMatpel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelGURU;
    private javax.swing.JLabel labelGuru;
    private javax.swing.JLabel labelMATPEL;
    private javax.swing.JLabel labelSTATUS;
    private javax.swing.JList listGuru;
    private javax.swing.JList listMatpel;
    private component.panel.Menu menu1;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JButton simpanGuru;
    private javax.swing.JButton simpanMatpel;
    private javax.swing.JSpinner spinnerJam;
    // End of variables declaration//GEN-END:variables

}
