/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Start.java
 *
 * Created on Nov 8, 2011, 11:01:03 PM
 */

package apjsd2;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author zaf
 */
public class Start extends javax.swing.JFrame {

    Query q;
    Generate g;

    /** Creates new form Start */
    public Start() {
        initComponents();
        q = new Query();
        g = new Generate();
        loadAwal();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuUtama = new component.panel.Menu();
        kalkulasi1 = new component.button.Kalkulasi();
        perbaikiData1 = new component.button.PerbaikiData();
        masukkanData1 = new component.button.MasukkanData();
        keluar1 = new component.button.Keluar();
        lihatJadwal1 = new component.button.LihatJadwal();
        kontrolUtama = new javax.swing.JPanel();
        awal = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        masukkanData = new javax.swing.JPanel();
        panelGuru = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        labelGURU = new javax.swing.JLabel();
        fieldGuru = new javax.swing.JTextField();
        labelNamaGuru = new javax.swing.JLabel();
        simpanGuru = new javax.swing.JButton();
        panelMatpel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        simpanMatpel = new javax.swing.JButton();
        inputMatpel = new javax.swing.JTextField();
        labelMatpel = new javax.swing.JLabel();
        labelGuru = new javax.swing.JLabel();
        comboBoxGuru = new javax.swing.JComboBox();
        labelMATPEL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spinnerJam = new javax.swing.JSpinner();
        lihatJadwal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        panel_senin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_senin = new javax.swing.JTable();
        panel_selasa = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabel_selasa = new javax.swing.JTable();
        panel_rabu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabel_rabu = new javax.swing.JTable();
        panel_kamis = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabel_kamis = new javax.swing.JTable();
        panel_jumat = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabel_jumat = new javax.swing.JTable();
        panel_sabtu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabel_sabtu = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        kalkulasi = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        senin = new javax.swing.JCheckBox();
        rabu = new javax.swing.JCheckBox();
        selasa = new javax.swing.JCheckBox();
        kamis = new javax.swing.JCheckBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jumat = new javax.swing.JCheckBox();
        sabtu = new javax.swing.JCheckBox();
        perbaikiData = new javax.swing.JPanel();
        guru = new javax.swing.JPanel();
        labelGURU1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        listGuru = new javax.swing.JList();
        fieldGuru1 = new javax.swing.JTextField();
        simpanGuru1 = new javax.swing.JButton();
        hapusGuru = new javax.swing.JButton();
        matpel = new javax.swing.JPanel();
        labelMATPEL1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        listMatpel = new javax.swing.JList();
        fieldMatpel = new javax.swing.JTextField();
        simpanMatpel1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelGuru1 = new javax.swing.JLabel();
        comboBoxGuru1 = new javax.swing.JComboBox();
        hapusMatpel = new javax.swing.JButton();
        spinnerJam1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusAksi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pengolah Jadwal Sekolah Dasar");
        setExtendedState(this.MAXIMIZED_BOTH);

        kalkulasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalkulasi1ActionPerformed(evt);
            }
        });

        perbaikiData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaikiData1ActionPerformed(evt);
            }
        });

        masukkanData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukkanData1ActionPerformed(evt);
            }
        });

        keluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar1ActionPerformed(evt);
            }
        });

        lihatJadwal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatJadwal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuUtamaLayout = new javax.swing.GroupLayout(menuUtama);
        menuUtama.setLayout(menuUtamaLayout);
        menuUtamaLayout.setHorizontalGroup(
            menuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masukkanData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perbaikiData1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kalkulasi1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lihatJadwal1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(keluar1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuUtamaLayout.setVerticalGroup(
            menuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masukkanData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perbaikiData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kalkulasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihatJadwal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kontrolUtama.setLayout(new java.awt.CardLayout());

        jLabel11.setFont(new java.awt.Font("Gentium", 1, 48));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html>\n<center>\nSELAMAT DATANG<br/>\nSISTEM INFORMASI PENGOLAH JADWAL<br/>\nSEKOLAH DASAR (SD)<br/>\n</center>");

        javax.swing.GroupLayout awalLayout = new javax.swing.GroupLayout(awal);
        awal.setLayout(awalLayout);
        awalLayout.setHorizontalGroup(
            awalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(awalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                .addContainerGap())
        );
        awalLayout.setVerticalGroup(
            awalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, awalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        kontrolUtama.add(awal, "card6");

        masukkanData.setBorder(null);

        panelGuru.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelGURU.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelGURU.setText("Guru");

        fieldGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldGuruKeyPressed(evt);
            }
        });

        labelNamaGuru.setText("Nama Guru");

        simpanGuru.setText("Simpan");
        simpanGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanGuruActionPerformed(evt);
            }
        });
        simpanGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                simpanGuruKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelGuruLayout = new javax.swing.GroupLayout(panelGuru);
        panelGuru.setLayout(panelGuruLayout);
        panelGuruLayout.setHorizontalGroup(
            panelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGURU)
                .addContainerGap(199, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
            .addGroup(panelGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(labelNamaGuru)
                    .addComponent(simpanGuru))
                .addContainerGap())
        );
        panelGuruLayout.setVerticalGroup(
            panelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGURU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNamaGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanGuru)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panelMatpel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        simpanMatpel.setText("Simpan");
        simpanMatpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanMatpelActionPerformed(evt);
            }
        });

        inputMatpel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputMatpelKeyPressed(evt);
            }
        });

        labelMatpel.setText("Mata pelajaran");

        labelGuru.setText("Guru");

        comboBoxGuru.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxGuruItemStateChanged(evt);
            }
        });
        comboBoxGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGuruActionPerformed(evt);
            }
        });
        comboBoxGuru.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                comboBoxGuruHierarchyChanged(evt);
            }
        });
        comboBoxGuru.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboBoxGuruPropertyChange(evt);
            }
        });
        comboBoxGuru.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                comboBoxGuruVetoableChange(evt);
            }
        });

        labelMATPEL.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelMATPEL.setText("Mata Pelajaran");

        jLabel1.setText("Jam");
        jLabel1.setToolTipText("Jumlah jam ajar dalam 1 minggu");

        spinnerJam.setToolTipText("Jumlah jam ajar dalam 1 minggu");
        spinnerJam.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelMatpelLayout = new javax.swing.GroupLayout(panelMatpel);
        panelMatpel.setLayout(panelMatpelLayout);
        panelMatpelLayout.setHorizontalGroup(
            panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMATPEL)
                .addContainerGap(62, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
            .addGroup(panelMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpanMatpel)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(panelMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(labelMatpel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatpelLayout.createSequentialGroup()
                        .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(spinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGuru)
                            .addComponent(comboBoxGuru, 0, 188, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelMatpelLayout.setVerticalGroup(
            panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMATPEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMatpel)
                .addGap(4, 4, 4)
                .addComponent(inputMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelGuru))
                .addGap(4, 4, 4)
                .addGroup(panelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanMatpel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout masukkanDataLayout = new javax.swing.GroupLayout(masukkanData);
        masukkanData.setLayout(masukkanDataLayout);
        masukkanDataLayout.setHorizontalGroup(
            masukkanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masukkanDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        masukkanDataLayout.setVerticalGroup(
            masukkanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masukkanDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masukkanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelMatpel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGuru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        kontrolUtama.add(masukkanData, "card2");

        jLabel4.setText("Pilih kelas");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panel_senin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Senin");

        tabel_senin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jam", "Pelajaran", "Guru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabel_senin);

        javax.swing.GroupLayout panel_seninLayout = new javax.swing.GroupLayout(panel_senin);
        panel_senin.setLayout(panel_seninLayout);
        panel_seninLayout.setHorizontalGroup(
            panel_seninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_seninLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_seninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_seninLayout.setVerticalGroup(
            panel_seninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_seninLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_selasa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Selasa");

        tabel_selasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jam", "Pelajaran", "Guru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabel_selasa);

        javax.swing.GroupLayout panel_selasaLayout = new javax.swing.GroupLayout(panel_selasa);
        panel_selasa.setLayout(panel_selasaLayout);
        panel_selasaLayout.setHorizontalGroup(
            panel_selasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_selasaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_selasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_selasaLayout.setVerticalGroup(
            panel_selasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_selasaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_rabu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Rabu");

        tabel_rabu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jam", "Pelajaran", "Guru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tabel_rabu);

        javax.swing.GroupLayout panel_rabuLayout = new javax.swing.GroupLayout(panel_rabu);
        panel_rabu.setLayout(panel_rabuLayout);
        panel_rabuLayout.setHorizontalGroup(
            panel_rabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rabuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_rabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_rabuLayout.setVerticalGroup(
            panel_rabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rabuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_kamis.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Kamis");

        tabel_kamis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jam", "Pelajaran", "Guru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tabel_kamis);

        javax.swing.GroupLayout panel_kamisLayout = new javax.swing.GroupLayout(panel_kamis);
        panel_kamis.setLayout(panel_kamisLayout);
        panel_kamisLayout.setHorizontalGroup(
            panel_kamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kamisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_kamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_kamisLayout.setVerticalGroup(
            panel_kamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kamisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_jumat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Jum'at");

        tabel_jumat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jam", "Pelajaran", "Guru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tabel_jumat);

        javax.swing.GroupLayout panel_jumatLayout = new javax.swing.GroupLayout(panel_jumat);
        panel_jumat.setLayout(panel_jumatLayout);
        panel_jumatLayout.setHorizontalGroup(
            panel_jumatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_jumatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_jumatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_jumatLayout.setVerticalGroup(
            panel_jumatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_jumatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_sabtu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Sabtu");

        tabel_sabtu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jam", "Pelajaran", "Guru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tabel_sabtu);

        javax.swing.GroupLayout panel_sabtuLayout = new javax.swing.GroupLayout(panel_sabtu);
        panel_sabtu.setLayout(panel_sabtuLayout);
        panel_sabtuLayout.setHorizontalGroup(
            panel_sabtuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sabtuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_sabtuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_sabtuLayout.setVerticalGroup(
            panel_sabtuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sabtuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lihatJadwalLayout = new javax.swing.GroupLayout(lihatJadwal);
        lihatJadwal.setLayout(lihatJadwalLayout);
        lihatJadwalLayout.setHorizontalGroup(
            lihatJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(867, Short.MAX_VALUE))
            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
            .addGroup(lihatJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_senin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_selasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_rabu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(lihatJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_kamis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_jumat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_sabtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        lihatJadwalLayout.setVerticalGroup(
            lihatJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lihatJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lihatJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_senin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_selasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_rabu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lihatJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_kamis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_jumat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_sabtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kontrolUtama.add(lihatJadwal, "card5");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        jButton1.setForeground(new java.awt.Color(60, 30, 210));
        jButton1.setText("BENTUK JADWAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        senin.setSelected(true);
        senin.setText("Senin");

        rabu.setSelected(true);
        rabu.setText("Rabu");

        selasa.setSelected(true);
        selasa.setText("Selasa");

        kamis.setSelected(true);
        kamis.setText("Kamis");

        jLabel3.setText("Jadwal reguler sekolah :");

        jumat.setSelected(true);
        jumat.setText("Jumat");

        sabtu.setSelected(true);
        sabtu.setText("Sabtu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(senin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rabu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kamis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jumat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sabtu))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senin)
                    .addComponent(selasa)
                    .addComponent(rabu)
                    .addComponent(kamis)
                    .addComponent(jumat)
                    .addComponent(sabtu))
                .addGap(57, 57, 57)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kalkulasiLayout = new javax.swing.GroupLayout(kalkulasi);
        kalkulasi.setLayout(kalkulasiLayout);
        kalkulasiLayout.setHorizontalGroup(
            kalkulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalkulasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(563, Short.MAX_VALUE))
        );
        kalkulasiLayout.setVerticalGroup(
            kalkulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalkulasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        kontrolUtama.add(kalkulasi, "card4");

        guru.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelGURU1.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelGURU1.setText("Guru");

        listGuru.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listGuruValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listGuru);

        fieldGuru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldGuru1ActionPerformed(evt);
            }
        });

        simpanGuru1.setText("Simpan");
        simpanGuru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanGuru1ActionPerformed(evt);
            }
        });

        hapusGuru.setText("Hapus");
        hapusGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusGuruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout guruLayout = new javax.swing.GroupLayout(guru);
        guru.setLayout(guruLayout);
        guruLayout.setHorizontalGroup(
            guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGURU1)
                .addContainerGap(158, Short.MAX_VALUE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addGroup(guruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldGuru1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(guruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(guruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpanGuru1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusGuru)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        guruLayout.setVerticalGroup(
            guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGURU1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldGuru1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanGuru1)
                    .addComponent(hapusGuru))
                .addContainerGap())
        );

        matpel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelMATPEL1.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        labelMATPEL1.setText("Mata Pelajaran");

        listMatpel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMatpelValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listMatpel);

        simpanMatpel1.setText("Simpan");
        simpanMatpel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanMatpel1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Guru");

        labelGuru1.setText("Jam");

        comboBoxGuru1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxGuru1ItemStateChanged(evt);
            }
        });
        comboBoxGuru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGuru1ActionPerformed(evt);
            }
        });
        comboBoxGuru1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                comboBoxGuru1HierarchyChanged(evt);
            }
        });
        comboBoxGuru1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboBoxGuru1PropertyChange(evt);
            }
        });
        comboBoxGuru1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                comboBoxGuru1VetoableChange(evt);
            }
        });

        hapusMatpel.setText("Hapus");
        hapusMatpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusMatpelActionPerformed(evt);
            }
        });

        spinnerJam1.setToolTipText("Jumlah jam ajar dalam 1 minggu");

        javax.swing.GroupLayout matpelLayout = new javax.swing.GroupLayout(matpel);
        matpel.setLayout(matpelLayout);
        matpelLayout.setHorizontalGroup(
            matpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matpelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(matpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMATPEL1)
                    .addGroup(matpelLayout.createSequentialGroup()
                        .addGroup(matpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGuru1)
                            .addComponent(spinnerJam1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(matpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxGuru1, 0, 170, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, matpelLayout.createSequentialGroup()
                        .addGroup(matpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(fieldMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
            .addGroup(matpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpanMatpel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusMatpel)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        matpelLayout.setVerticalGroup(
            matpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMATPEL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(matpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGuru1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(matpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxGuru1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerJam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(matpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanMatpel1)
                    .addComponent(hapusMatpel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout perbaikiDataLayout = new javax.swing.GroupLayout(perbaikiData);
        perbaikiData.setLayout(perbaikiDataLayout);
        perbaikiDataLayout.setHorizontalGroup(
            perbaikiDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perbaikiDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(512, Short.MAX_VALUE))
        );
        perbaikiDataLayout.setVerticalGroup(
            perbaikiDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perbaikiDataLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(perbaikiDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(guru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(matpel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        kontrolUtama.add(perbaikiData, "card3");

        statusAksi.setColumns(20);
        statusAksi.setFont(new java.awt.Font("DejaVu Sans", 3, 14));
        statusAksi.setRows(5);
        jScrollPane1.setViewportView(statusAksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(kontrolUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kontrolUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perbaikiData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbaikiData1ActionPerformed
        // TODO add your handling code here:
        loadPerbaikiData();
    }//GEN-LAST:event_perbaikiData1ActionPerformed

    private void masukkanData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukkanData1ActionPerformed
        // TODO add your handling code here:
        loadMasukkanData();
        
    }//GEN-LAST:event_masukkanData1ActionPerformed

    private void fieldGuruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldGuruKeyPressed
        // TODO add your handling code here:
        simpanGuru.setEnabled(true);
}//GEN-LAST:event_fieldGuruKeyPressed

    private void simpanGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanGuruActionPerformed
        // TODO add your handling code here:
        if (fieldGuru.getText().equals("")){
            statusAksi.append("Error, field must be fill!\n\n");
        } else {
            if (q.insertGuru(fieldGuru.getText())){
                statusAksi.append(fieldGuru.getText()+" --> added\n\n");
            } else {
                statusAksi.append("Error!\n\n");
            }
            comboBoxGuru.addItem(fieldGuru.getText());
            simpanGuru.setEnabled(false);
            comboBoxGuru.setEnabled(false);
            fieldGuru.setText("");
            loadMasukkanData();
        }
}//GEN-LAST:event_simpanGuruActionPerformed

    private void simpanGuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_simpanGuruKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_simpanGuruKeyTyped

    private void simpanMatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanMatpelActionPerformed
        // TODO add your handling code here:
        if (inputMatpel.getText().equals("")){
            statusAksi.append("Error, field must be fill!\n\n");
        } else {
            if (q.insertMatpel(inputMatpel.getText(), spinnerJam.getValue(), comboBoxGuru.getSelectedItem())){
                statusAksi.append(inputMatpel.getText()+" by "+comboBoxGuru.getSelectedItem()+" for "+spinnerJam.getValue()+" hours each week --> added\n\n");
            } else {
                statusAksi.append("Error!\n\n");
            }
            simpanMatpel.setEnabled(false);
            spinnerJam.setEnabled(false);
            comboBoxGuru.setEnabled(false);
            inputMatpel.setText("");
        }
}//GEN-LAST:event_simpanMatpelActionPerformed

    private void inputMatpelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMatpelKeyPressed
        // TODO add your handling code here:
        simpanMatpel.setEnabled(true);
        spinnerJam.setEnabled(true);
        comboBoxGuru.setEnabled(true);
}//GEN-LAST:event_inputMatpelKeyPressed

    private void comboBoxGuruItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxGuruItemStateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruItemStateChanged

    private void comboBoxGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGuruActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruActionPerformed

    private void comboBoxGuruHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_comboBoxGuruHierarchyChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruHierarchyChanged

    private void comboBoxGuruPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboBoxGuruPropertyChange
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruPropertyChange

    private void comboBoxGuruVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_comboBoxGuruVetoableChange
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuruVetoableChange

    private void listGuruValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listGuruValueChanged
        // TODO add your handling code here:
        fieldGuru1.setText((String)listGuru.getSelectedValue());
        simpanGuru1.setEnabled(true);
        hapusGuru.setEnabled(true);
}//GEN-LAST:event_listGuruValueChanged

    private void simpanGuru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanGuru1ActionPerformed
        // TODO add your handling code here:
        String guruLama = (String)listGuru.getSelectedValue();
        String guruBaru = fieldGuru1.getText();
        if (q.updateGuru(guruLama, guruBaru)){
            statusAksi.append(guruLama+" --> "+guruBaru+"\n\n");
        } else {
            statusAksi.append("Error!\n\n");
        }
        loadPerbaikiData();
    }//GEN-LAST:event_simpanGuru1ActionPerformed

    private void hapusGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusGuruActionPerformed
        // TODO add your handling code here:
        String guru1 = (String)listGuru.getSelectedValue();
        if (q.deleteGuru(guru1)){
            statusAksi.append(guru1+" --> removed (matpel which handled by "+guru1+" was moved to some guru)\n\n");
        } else {
            statusAksi.append("Error!\n\n");
        }
        loadPerbaikiData();
    }//GEN-LAST:event_hapusGuruActionPerformed

    private void listMatpelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMatpelValueChanged
        // TODO add your handling code here:
        fieldMatpel.setText((String)listMatpel.getSelectedValue());
        simpanMatpel1.setEnabled(true);
        spinnerJam1.setEnabled(true);
        comboBoxGuru1.setEnabled(true);
        hapusMatpel.setEnabled(true);
        q.setHighlightMatpel(listMatpel.getSelectedValue(), spinnerJam1, comboBoxGuru1);
    }//GEN-LAST:event_listMatpelValueChanged

    private void simpanMatpel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanMatpel1ActionPerformed
        // TODO add your handling code here:
        String matpelLama = (String)listMatpel.getSelectedValue();
        String matpelBaru = fieldMatpel.getText();
        Object jam = spinnerJam1.getValue();
        String guru2 = (String)comboBoxGuru1.getSelectedItem();
        if (q.updateMatpel(matpelLama, matpelBaru, jam, guru2)){
            statusAksi.append(matpelLama+" --> "+matpelBaru+", "+guru2+" for "+jam+" hours each week!\n\n");
        } else {
            statusAksi.append("Error!\n\n");
        }
        loadPerbaikiData();
    }//GEN-LAST:event_simpanMatpel1ActionPerformed

    private void comboBoxGuru1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxGuru1ItemStateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuru1ItemStateChanged

    private void comboBoxGuru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGuru1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuru1ActionPerformed

    private void comboBoxGuru1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_comboBoxGuru1HierarchyChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuru1HierarchyChanged

    private void comboBoxGuru1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboBoxGuru1PropertyChange
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuru1PropertyChange

    private void comboBoxGuru1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_comboBoxGuru1VetoableChange
        // TODO add your handling code here:
}//GEN-LAST:event_comboBoxGuru1VetoableChange

    private void hapusMatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusMatpelActionPerformed
        // TODO add your handling code here:
        String matpel1 = (String)listMatpel.getSelectedValue();
        if (q.deleteMatpel(matpel1)){
            statusAksi.append(matpel1+" --> removed\n\n");
        } else {
            statusAksi.append("Error!\n\n");
        }
        loadPerbaikiData();
    }//GEN-LAST:event_hapusMatpelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        generate();
}//GEN-LAST:event_jButton1ActionPerformed

    private void kalkulasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalkulasi1ActionPerformed
        // TODO add your handling code here:
        loadKalkulasi();
    }//GEN-LAST:event_kalkulasi1ActionPerformed

    private void lihatJadwal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatJadwal1ActionPerformed
        // TODO add your handling code here:
        loadLihatJadwal();
    }//GEN-LAST:event_lihatJadwal1ActionPerformed

    private void keluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_keluar1ActionPerformed

    private void fieldGuru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldGuru1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldGuru1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loadLihatJadwal();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }
    void loadAwal(){
        hiddenAllCard();
        awal.setVisible(true);
    }
    void loadMasukkanData(){
        hiddenAllCard();
        masukkanData.setVisible(true);
        comboBoxGuru.removeAllItems();
        q.setComboBoxGuru(comboBoxGuru);
        simpanGuru.setEnabled(false);
        simpanMatpel.setEnabled(false);
        spinnerJam.setEnabled(false);
        comboBoxGuru.setEnabled(false);
    }
    void loadPerbaikiData(){
        hiddenAllCard();
        perbaikiData.setVisible(true);
        listGuru.removeAll();
        q.setListGuru(listGuru);
        listMatpel.removeAll();
        q.setListMatpel(listMatpel);
        comboBoxGuru1.removeAllItems();
        q.setComboBoxGuru(comboBoxGuru1);
        simpanGuru1.setEnabled(false);
        simpanMatpel1.setEnabled(false);
        spinnerJam1.setEnabled(false);
        comboBoxGuru.setEnabled(false);
        hapusGuru.setEnabled(false);
        hapusMatpel.setEnabled(false);
    }
    void loadKalkulasi(){
        hiddenAllCard();
        kalkulasi.setVisible(true);
    }
    void loadLihatJadwal(){
        hiddenAllCard();
        lihatJadwal.setVisible(true);
        showJadwal(jComboBox1.getSelectedIndex()+1);
    }
    void hiddenAllCard(){
        awal.setVisible(false);
        masukkanData.setVisible(false);
        perbaikiData.setVisible(false);
        kalkulasi.setVisible(false);
        lihatJadwal.setVisible(false);
    }
    
    
    // bagian kalkulasi jadwal
    void generate(){
        if (q.isJadwalEmptyResult()){
            String s = "The schedule was calculated before!\nDid u truncate that and generate new one?";
            int ops = JOptionPane.showConfirmDialog(this.rootPane, s, "Warning!", JOptionPane.YES_NO_OPTION);
            if (ops == 0) {
                q.truncateJadwal();
                statusAksi.append("Schedule was truncate, click the Generate Button again to generate new one!\n\n");
            } else {
                statusAksi.append("Schedule not regenerated!\n\n");
            }
        } else {
            statusAksi.append("Generating...");
            //g.buildLinkedList();
            g.insertListToDatabase(this.getJam(), this.getKelas(), this.getHari());
            //g.show();
            if (g.complete){
                statusAksi.append(" Done!\n\n");
            } else {
                statusAksi.append(" Error!\nTotal of all schedule hours overload from total hours one week!\n\n");
                q.truncateJadwal();
            }
        }
        loadKalkulasi();
    }
    int[] getJam(){
        int[] x = new int[6];
        x[0] = 1; x[1] = 2; x[2] = 3; x[3] = 4; x[4] = 5; x[5] = 6;
        return x;
    }
    int[] getKelas(){
        int[] x = new int[6];
        x[0] = 1; x[1] = 2; x[2] = 3; x[3] = 4; x[4] = 5; x[5] = 6;
        return x;
    }
    String[] getHari(){
        // asumsi jumlah hari reguler yang digunakan adalah 6 hari
        int i = 0;
        String[] x = new String[6];
        if (senin.isSelected()) x[0] = "Senin";
        if (selasa.isSelected()) x[1] = "Selasa";
        if (rabu.isSelected()) x[2] = "Rabu";
        if (kamis.isSelected()) x[3] = "Kamis";
        if (jumat.isSelected()) x[4] = "Jumat";
        if (sabtu.isSelected()) x[5] = "Sabtu";
        return x;
    }
    
    
    // bagian untuk menampilkan jadwal
    void showJadwal(int kelas){
        int jamCol = 25, pelajaranCol = 150, guruCol = 100;
        // hari senin
        try {
            List<Jadwal> senin_list = new ArrayList<Jadwal>();
            hasil = q.getJadwalByHari(kelas, "senin");
            while (hasil.next()){
                Jadwal jadwal_senin = new Jadwal();
                jadwal_senin.setJam(hasil.getInt("jam"));
                jadwal_senin.setPelajaran(hasil.getString("matpel"));
                jadwal_senin.setGuru(hasil.getString("guru"));
                senin_list.add(jadwal_senin);
            }
            TableModel senin_model = new TabelModelJadwal(senin_list);
            tabel_senin.setModel(senin_model);
            tabel_senin.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            TableColumn jam_col = tabel_senin.getColumnModel().getColumn(0);
            jam_col.setPreferredWidth(jamCol);
            TableColumn pelajaran_col = tabel_senin.getColumnModel().getColumn(1);
            pelajaran_col.setPreferredWidth(pelajaranCol);
            TableColumn guru_col = tabel_senin.getColumnModel().getColumn(2);
            guru_col.setPreferredWidth(guruCol);
        } catch (SQLException ex) {
            statusAksi.append(ex.getMessage()+"\n\n");
        }
        // hari selasa
        try {
            List<Jadwal> selasa_list = new ArrayList<Jadwal>();
            hasil = q.getJadwalByHari(kelas, "selasa");
            while (hasil.next()){
                Jadwal jadwal_selasa = new Jadwal();
                jadwal_selasa.setJam(hasil.getInt("jam"));
                jadwal_selasa.setPelajaran(hasil.getString("matpel"));
                jadwal_selasa.setGuru(hasil.getString("guru"));
                selasa_list.add(jadwal_selasa);
            }
            TableModel selasa_model = new TabelModelJadwal(selasa_list);
            tabel_selasa.setModel(selasa_model);
            tabel_selasa.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            TableColumn jam_col = tabel_selasa.getColumnModel().getColumn(0);
            jam_col.setPreferredWidth(jamCol);
            TableColumn pelajaran_col = tabel_selasa.getColumnModel().getColumn(1);
            pelajaran_col.setPreferredWidth(pelajaranCol);
            TableColumn guru_col = tabel_selasa.getColumnModel().getColumn(2);
            guru_col.setPreferredWidth(guruCol);
        } catch (SQLException ex) {
            statusAksi.append(ex.getMessage()+"\n\n");
        }
        // hari rabu
        try {
            List<Jadwal> rabu_list = new ArrayList<Jadwal>();
            hasil = q.getJadwalByHari(kelas, "rabu");
            while (hasil.next()){
                Jadwal jadwal_rabu = new Jadwal();
                jadwal_rabu.setJam(hasil.getInt("jam"));
                jadwal_rabu.setPelajaran(hasil.getString("matpel"));
                jadwal_rabu.setGuru(hasil.getString("guru"));
                rabu_list.add(jadwal_rabu);
            }
            TableModel rabu_model = new TabelModelJadwal(rabu_list);
            tabel_rabu.setModel(rabu_model);
            tabel_rabu.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            TableColumn jam_col = tabel_rabu.getColumnModel().getColumn(0);
            jam_col.setPreferredWidth(jamCol);
            TableColumn pelajaran_col = tabel_rabu.getColumnModel().getColumn(1);
            pelajaran_col.setPreferredWidth(pelajaranCol);
            TableColumn guru_col = tabel_rabu.getColumnModel().getColumn(2);
            guru_col.setPreferredWidth(guruCol);
        } catch (SQLException ex) {
            statusAksi.append(ex.getMessage()+"\n\n");
        }
        // hari kamis
        try {
            List<Jadwal> kamis_list = new ArrayList<Jadwal>();
            hasil = q.getJadwalByHari(kelas, "kamis");
            while (hasil.next()){
                Jadwal jadwal_kamis = new Jadwal();
                jadwal_kamis.setJam(hasil.getInt("jam"));
                jadwal_kamis.setPelajaran(hasil.getString("matpel"));
                jadwal_kamis.setGuru(hasil.getString("guru"));
                kamis_list.add(jadwal_kamis);
            }
            TableModel kamis_model = new TabelModelJadwal(kamis_list);
            tabel_kamis.setModel(kamis_model);
            tabel_kamis.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            TableColumn jam_col = tabel_kamis.getColumnModel().getColumn(0);
            jam_col.setPreferredWidth(jamCol);
            TableColumn pelajaran_col = tabel_kamis.getColumnModel().getColumn(1);
            pelajaran_col.setPreferredWidth(pelajaranCol);
            TableColumn guru_col = tabel_kamis.getColumnModel().getColumn(2);
            guru_col.setPreferredWidth(guruCol);
        } catch (SQLException ex) {
            statusAksi.append(ex.getMessage()+"\n\n");
        }
        // hari jumat
        try {
            List<Jadwal> jumat_list = new ArrayList<Jadwal>();
            hasil = q.getJadwalByHari(kelas, "jumat");
            while (hasil.next()){
                Jadwal jadwal_jumat = new Jadwal();
                jadwal_jumat.setJam(hasil.getInt("jam"));
                jadwal_jumat.setPelajaran(hasil.getString("matpel"));
                jadwal_jumat.setGuru(hasil.getString("guru"));
                jumat_list.add(jadwal_jumat);
            }
            TableModel jumat_model = new TabelModelJadwal(jumat_list);
            tabel_jumat.setModel(jumat_model);
            tabel_jumat.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            TableColumn jam_col = tabel_jumat.getColumnModel().getColumn(0);
            jam_col.setPreferredWidth(jamCol);
            TableColumn pelajaran_col = tabel_jumat.getColumnModel().getColumn(1);
            pelajaran_col.setPreferredWidth(pelajaranCol);
            TableColumn guru_col = tabel_jumat.getColumnModel().getColumn(2);
            guru_col.setPreferredWidth(guruCol);
        } catch (SQLException ex) {
            statusAksi.append(ex.getMessage()+"\n\n");
        }
        // hari sabtu
        try {
            List<Jadwal> sabtu_list = new ArrayList<Jadwal>();
            hasil = q.getJadwalByHari(kelas, "sabtu");
            while (hasil.next()){
                Jadwal jadwal_sabtu = new Jadwal();
                jadwal_sabtu.setJam(hasil.getInt("jam"));
                jadwal_sabtu.setPelajaran(hasil.getString("matpel"));
                jadwal_sabtu.setGuru(hasil.getString("guru"));
                sabtu_list.add(jadwal_sabtu);
            }
            TableModel sabtu_model = new TabelModelJadwal(sabtu_list);
            tabel_sabtu.setModel(sabtu_model);
            tabel_sabtu.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            TableColumn jam_col = tabel_sabtu.getColumnModel().getColumn(0);
            jam_col.setPreferredWidth(jamCol);
            TableColumn pelajaran_col = tabel_sabtu.getColumnModel().getColumn(1);
            pelajaran_col.setPreferredWidth(pelajaranCol);
            TableColumn guru_col = tabel_sabtu.getColumnModel().getColumn(2);
            guru_col.setPreferredWidth(guruCol);
        } catch (SQLException ex) {
            statusAksi.append(ex.getMessage()+"\n\n");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel awal;
    private javax.swing.JComboBox comboBoxGuru;
    private javax.swing.JComboBox comboBoxGuru1;
    private javax.swing.JTextField fieldGuru;
    private javax.swing.JTextField fieldGuru1;
    private javax.swing.JTextField fieldMatpel;
    private javax.swing.JPanel guru;
    private javax.swing.JButton hapusGuru;
    private javax.swing.JButton hapusMatpel;
    private javax.swing.JTextField inputMatpel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JCheckBox jumat;
    private javax.swing.JPanel kalkulasi;
    private component.button.Kalkulasi kalkulasi1;
    private javax.swing.JCheckBox kamis;
    private component.button.Keluar keluar1;
    private javax.swing.JPanel kontrolUtama;
    private javax.swing.JLabel labelGURU;
    private javax.swing.JLabel labelGURU1;
    private javax.swing.JLabel labelGuru;
    private javax.swing.JLabel labelGuru1;
    private javax.swing.JLabel labelMATPEL;
    private javax.swing.JLabel labelMATPEL1;
    private javax.swing.JLabel labelMatpel;
    private javax.swing.JLabel labelNamaGuru;
    private javax.swing.JPanel lihatJadwal;
    private component.button.LihatJadwal lihatJadwal1;
    private javax.swing.JList listGuru;
    private javax.swing.JList listMatpel;
    private javax.swing.JPanel masukkanData;
    private component.button.MasukkanData masukkanData1;
    private javax.swing.JPanel matpel;
    private component.panel.Menu menuUtama;
    private javax.swing.JPanel panelGuru;
    private javax.swing.JPanel panelMatpel;
    private javax.swing.JPanel panel_jumat;
    private javax.swing.JPanel panel_kamis;
    private javax.swing.JPanel panel_rabu;
    private javax.swing.JPanel panel_sabtu;
    private javax.swing.JPanel panel_selasa;
    private javax.swing.JPanel panel_senin;
    private javax.swing.JPanel perbaikiData;
    private component.button.PerbaikiData perbaikiData1;
    private javax.swing.JCheckBox rabu;
    private javax.swing.JCheckBox sabtu;
    private javax.swing.JCheckBox selasa;
    private javax.swing.JCheckBox senin;
    private javax.swing.JButton simpanGuru;
    private javax.swing.JButton simpanGuru1;
    private javax.swing.JButton simpanMatpel;
    private javax.swing.JButton simpanMatpel1;
    private javax.swing.JSpinner spinnerJam;
    private javax.swing.JSpinner spinnerJam1;
    private javax.swing.JTextArea statusAksi;
    private javax.swing.JTable tabel_jumat;
    private javax.swing.JTable tabel_kamis;
    private javax.swing.JTable tabel_rabu;
    private javax.swing.JTable tabel_sabtu;
    private javax.swing.JTable tabel_selasa;
    private javax.swing.JTable tabel_senin;
    // End of variables declaration//GEN-END:variables

    private java.sql.ResultSet hasil;
}
